### PR TITLE
[WIP] Add a resource page

### PR DESCRIPTION
**Pull request by acnagy**
Discussion is in https://github.com/travis-ci/travis-foundation/issues/59

### CODE REVIEW

**Comment by alicetragedy** [comment]
I hope you don't mind—I've added a resource for gender :)
I think the page looks great so far. One thing that came to mind when I added an extra resource is that maybe we could move all the content to an external yaml file (with the link, the category and a description for each resource) and could iterate over each item on the resources page. It would make it slightly easier to add a resource quickly, and might be cleaner once we have a lot more resources. (We've already used this in other pages, see `projects.yml`).
I'd love to know what you think!

**Comment by acnagy** [comment]
@alicetragedy Awesome - thank you! That gender section was looking blank...
Moving the data over to an external yaml file sounds great to me - definitely more maintainable as it expands. 

However - a quick question - shall we do one for the whole resources page, perhaps something in the format of:
`resources.yml`
```
name: Travis Foundation
url: http://foundation.travis-ci.org/
description: an awesome foundation
section: diversity
```
or, shall we do different yamls for each section? Such as:
`diversity.yml`
```
name: Travis Foundation
url: http://foundation.travis-ci.org/
description: an awesome foundation
```
I'm really only seeing an advantage for breaking up resources by topic if there's any expectation at all to split up the page, so I'm leaning toward the first way of setting up that file. What do you think?

**Comment by alicetragedy** [comment]
@acnagy I definitely agree with you that a single yamls for all resources makes more sense, because it's more consistent with the way the resources page will be set up. If at any point in the future we end up, for whatever reason, needing to split up the page—we can always change the `resources.yml` accordingly :) Please go ahead and let me know if there's any way I can help or anything I can give feedback on!

**Comment by acnagy** [comment]
Sounds good @alicetragedy - will get that moved over asap 👍

**Pull request merged**
