### PR TITLE
Add Atom feed for blog posts

### PR DESCRIPTION
**Pull request by eugeneius**
I wanted to subscribe to the blog but there was no feed.

I'm not that familiar with Jekyll, so I based this on [the feed for the Travis CI blog](https://github.com/travis-ci/blog-travis-ci-com/blob/gh-pages/blog.xml).

### CODE REVIEW

**Comment by pfctdayelise** [comment]
Kind of a shame that [you were all like](http://foundation.travis-ci.org/2013/12/10/hello-world/) "want a feed? submit a PR!" and someone has done just that but only got crickets. Is there anything more needed before merging this?

**Comment by eugeneius** [comment]
I've rebased to resolve a conflict with some recent design changes.

@lislis you've been working on this repo recently, any chance you could review this?

**Comment by lislis** [comment]
Hey @eugeneius! Thanks for opening the PR and sorry that this took so long. Looks like I'm in charge of the repo now...  
Can you push your rebase? I'd like to see if everything is working and then get this merged ASAP :)

**Comment by eugeneius** [comment]
I pushed the rebased commit yesterday, so everything is up to date here.

I'm not sure why Travis didn't run - it looks like no builds have been run for about a month:
https://travis-ci.org/travis-ci/travis-foundation/builds

**Comment by lislis** [comment]
@eugeneius I tested it locally and everything looks good :)
Thanks for working on it and your patience!
Oh yeah

**Comment by anikalindtner** [comment]
@eugeneius thank you soo much! And so sorry about that, the PR totally got overlooked :/ But so awesome that we have it live now. :sparkles: Would you be interested in getting stickers as a tiny sorry and thank you? We are in the process of ordering the first batch of our new amazing logo and I'd love to send you some!

**Comment by eugeneius** [comment]
@lislis thanks for the merge, and the gif! :grin: 

@anikalindtner that would be great! I just sent you an email. :email:

**Pull request merged**
