### PR TITLE
Update website

### PR DESCRIPTION
**Pull request by lislis**
- Upgrade to Jekyll 3
- add HTML Proofer to Travis and switch to trusty 
- add logo page

### CODE REVIEW

**Comment by alicetragedy** [comment]
Hey @lislis, do you need someone to review this or is it a WIP? If it needs reviewing you can definitely add me as a reviewer and I can take a look maybe today already or next week. Thanks for all your work ✨

**Comment by lislis** [comment]
@alicetragedy hey! Unfortunately it's not done :/ The Stripe Checkout does require some server logic that the static site doesn't give us. There are three options:
- try to write some Rack middleware
- wrap the Jekyll page into a Sinatra app
- use AWS lambda
I still need to think what makes most sense for this. It's literally one backend function we need and I want to keep the overhead as low as possible

**Comment by alicetragedy** [comment]
@lislis no worries, makes total sense. I think for the similar situation we had with RGSoC (for the campaign) we used a separate Rails app, which in retrospect comes with some overhead, so take your time considering the options and feel free to ping me if you need anything, I'd be happy to help.

**Comment by lislis** [comment]
Split up in #83 and #84

**Pull request closed without merging**
