### PR TITLE
add rgsoc blog post and folder for blog images

### PR DESCRIPTION
**Pull request by alicetragedy**
would love some :sparkles: feedback/suggestions :sparkles: on:  
- folder structure for the images used in blog posts
- better formatting/styling for the quotes (ie. how to separate quote from quote author)

### CODE REVIEW

**Comment by lislis** [comment]
I think the styling of the quotes is pretty ok. If you want maybe just add some margin to `<em>` within the blockquote to make some space for the author?  
About the folder structure. It might be a nice idea to prefix the image names with the date of the post they belong to? Makes it easier to find them later :D

**Comment by alicetragedy** [comment]
thank you for the suggestions @lislis! I've made changes accordingly.

**Comment by lislis** [comment]
@alicetragedy :dope: I'd say it's good to go. Do you have a schedule or should I just hit the green button?

**Comment by lislis** [comment]
nvm :D

**Comment by anikalindtner** [comment]
WHOOOOP! such fast MERGING :sparkles:

**Comment by alicetragedy** [comment]
:tada: :confetti_ball:

**Pull request merged**
