### PR TITLE
Add some link love, and fix a few sponsor names

### PR DESCRIPTION
**Pull request by svenfuchs**
I wasn't quite sure where to link to for SoundDrop. Maybe also double check the other projects?

Also, Basecamp has a lower case `c`, and innoQ a lowercase `i` :)

### CODE REVIEW

**Comment by anikalindtner** [comment]
thanks @svenfuchs!

**Comment by alicetragedy** [comment]
thanks @svenfuchs! ✨

**Comment by svenfuchs** [comment]
@anikalindtner @alicetragedy wow you are fast. i've just fixed one link here: https://github.com/travis-ci/travis-foundation/commit/13cd89dd59149dab342b554dff33866969cfad36

**Comment by svenfuchs** [comment]
now that i think about it, we could have linked all projects to our teams app. like https://teams.railsgirlssummerofcode.org/projects/120-qutebrowser. but yeah :)

**Comment by anikalindtner** [comment]
@svenfuchs yeah, i also thought about that when linking the projects in the map. i can maybe change them there to the teams app.

**Pull request merged**
